'use strict';

const path = require('node:path');

function source(wpaiRoot, label, relativePath) {
  return {
    label,
    relativePath,
    path: path.join(wpaiRoot, relativePath),
  };
}

function getCompanyAuthoritySources(wpaiRoot) {
  return [
    source(wpaiRoot, 'WPAI operating context', 'WPAI-CONTEXT.md'),
    source(wpaiRoot, 'Portfolio activation roadmap', 'WPAI-ROADMAP.md'),
    source(wpaiRoot, 'Revenue sequencing plan', 'REVENUE-PLAN.md'),
    source(wpaiRoot, 'Empire production constitution', 'SOULv2.0.0.md'),
  ];
}

/**
 * Fixed company registry. These records describe the portfolio structure and
 * operating boundaries; they are deliberately not discovered from arbitrary
 * folders or editable from the renderer. That keeps folder-opening IPC
 * allowlisted and stops an attractive dashboard from becoming an execution
 * surface for every repository in the company.
 */
function getDivisionDefinitions(wpaiRoot) {
  const division = (definition) => {
    const { directoryName, sourceDocuments, supplementalSignal, ...properties } = definition;
    return {
      ...properties,
      directory: path.join(wpaiRoot, directoryName),
      sourceDocuments: sourceDocuments.map(({ label, relativePath }) => source(wpaiRoot, label, relativePath)),
      supplementalSignal: supplementalSignal
      ? source(wpaiRoot, supplementalSignal.label, supplementalSignal.relativePath)
      : null,
    };
  };

  return [
    division({
      id: 'music',
      label: 'Music',
      category: 'Revenue engine',
      directoryName: 'Music',
      description: 'AI-assisted rock, metal, and country-crossover catalog; the portfolio funding engine and release-story anchor.',
      phase: 'active',
      phaseLabel: 'Active funding engine',
      statusState: 'needs-verification',
      statusLabel: 'RECONCILE RELEASE SIGNALS',
      statusNote: 'Local catalog and dated revenue sources use different track and release counts. Verify rights, metadata, distribution, and storefront state in the established Music workflow before acting.',
      activationGate: 'Director approves rights, metadata, distribution, and promotion through the existing Music and StudioOps release workflow.',
      operatingBoundary: 'Music owns the catalog, rights record, metadata, and release decisions. RickPrime only exposes its authoritative sources and folder handoff.',
      sourceDocuments: [
        { label: 'Music operating overview', relativePath: 'Music/README.md' },
        { label: 'Music catalog', relativePath: 'Music/CATALOG.md' },
        { label: 'Distribution plan', relativePath: 'Music/DISTRIBUTION-PLAN.md' },
      ],
    }),
    division({
      id: 'software',
      label: 'Software',
      category: 'Products and internal systems',
      directoryName: 'Software',
      description: 'Internal controls, local knowledge systems, developer tools, and commercial software products. Its individual repositories remain in the Project Fleet.',
      phase: 'active',
      phaseLabel: 'Active internal and product lane',
      statusState: 'needs-verification',
      statusLabel: 'VERIFY COMMERCIAL SNAPSHOTS',
      statusNote: 'RepoForge and Mixin Field Manual launch statements are dated plan records. Their repositories are present, but storefront and campaign state must be verified before commercial decisions.',
      activationGate: 'Distribution-first rule: do not start unrelated products until the existing sellable lines and their delivery paths are verified.',
      operatingBoundary: 'Each repository retains its own instructions, runtime ownership, and launch path. RickPrime has only registered handoffs and read-first controls.',
      sourceDocuments: [
        { label: 'Revenue sequencing plan', relativePath: 'REVENUE-PLAN.md' },
        { label: 'Portfolio activation roadmap', relativePath: 'WPAI-ROADMAP.md' },
        { label: 'RickPrime workstation boundary', relativePath: 'Software/RickPrime/README.md' },
      ],
    }),
    division({
      id: 'gaming',
      label: 'Gaming',
      category: 'Audience and game development',
      directoryName: 'Gaming',
      description: 'Minecraft modding and original-game work under the Mrwizard94 identity, including the Astral Sorcery port worktree.',
      phase: 'active',
      phaseLabel: 'Active external project lane',
      statusState: 'needs-verification',
      statusLabel: 'VERIFY PUBLIC RELEASE STATE',
      statusNote: 'The division source identifies a local Astral Sorcery port path, but a public CurseForge or Modrinth release must be independently confirmed before it is treated as shipped.',
      activationGate: 'Public-ready Astral Sorcery port under WPAI/Mrwizard94 branding, with platform and release requirements handled by the Gaming workflow.',
      operatingBoundary: 'Gaming owns mod source, platform compliance, builds, and public-release actions. RickPrime provides awareness only.',
      sourceDocuments: [
        { label: 'Gaming operating overview', relativePath: 'Gaming/README.md' },
        { label: 'Portfolio activation roadmap', relativePath: 'WPAI-ROADMAP.md' },
      ],
      supplementalSignal: { label: 'Astral Sorcery port worktree', relativePath: 'Gaming/Minecraft/Mods-1.20.1-Forge/Astral_Sorcery_Port' },
    }),
    division({
      id: 'graphics',
      label: 'Graphics',
      category: 'Shared creative service',
      directoryName: 'Graphics',
      description: 'Visual identity, album art, video assets, thumbnails, and future client-art capability shared across WPAI.',
      phase: 'support',
      phaseLabel: 'Support lane / conditional activation',
      statusState: 'director-decision',
      statusLabel: 'ACTIVATION GATE RECORDED',
      statusNote: 'The division is intentionally a support function until consistent Music release cadence or external art demand makes a dedicated operating lane necessary.',
      activationGate: 'Activate as a dedicated lane when Music needs recurring release art or external art requests create sustained demand.',
      operatingBoundary: 'Brand guidance defines shared visual direction; project teams own their final assets and any external commitments.',
      sourceDocuments: [
        { label: 'Graphics operating overview', relativePath: 'Graphics/README.md' },
        { label: 'Brand voice and positioning', relativePath: 'Brand/BRAND-VOICE.md' },
      ],
    }),
    division({
      id: 'brand',
      label: 'Brand',
      category: 'Shared operating standard',
      directoryName: 'Brand',
      description: 'The shared identity, transparency stance, and language system used by every customer-facing WPAI division.',
      phase: 'support',
      phaseLabel: 'Active shared standard',
      statusState: 'verified',
      statusLabel: 'SOURCE STANDARD DETECTED',
      statusNote: 'The Brand Voice source is present and provides the portfolio-wide disclosure, authorship, and tone standard. Market-facing copy still requires director review.',
      activationGate: 'Always active as the shared constraint for public communication; no independent launch gate exists.',
      operatingBoundary: 'Brand sets the shared voice. Division owners and the director approve context-specific claims and external publication.',
      sourceDocuments: [
        { label: 'Brand voice and positioning', relativePath: 'Brand/BRAND-VOICE.md' },
        { label: 'WPAI operating context', relativePath: 'WPAI-CONTEXT.md' },
      ],
    }),
    division({
      id: 'games',
      label: 'Games / Cinderforge',
      category: 'Original game incubation',
      directoryName: 'Games',
      description: 'The Cinderforge rhythm-action roguelite concept, designed to turn WPAI-owned music and stems into a game-and-soundtrack flywheel.',
      phase: 'review',
      phaseLabel: 'Concept review / vertical-slice gate',
      statusState: 'research-synthesis',
      statusLabel: 'DIRECTOR GREEN-LIGHT REQUIRED',
      statusNote: 'The available concept brief is an investor-oriented research synthesis and recommendation, not a verified production plan or public announcement.',
      activationGate: 'Director selects the concept direction, track candidates, and vertical-slice scope before production work begins.',
      operatingBoundary: 'Games owns its concept and eventual production plan. Music rights and stems remain governed by the Music release and rights workflow.',
      sourceDocuments: [
        { label: 'Cinderforge concept brief', relativePath: 'Games/GAME-CONCEPT-BRIEF.md' },
        { label: 'Brand voice and positioning', relativePath: 'Brand/BRAND-VOICE.md' },
      ],
    }),
    division({
      id: 'ai-research',
      label: 'AI Research',
      category: 'Long-horizon research',
      directoryName: 'AI-Research',
      description: 'Efficiency, novel computing architectures, VRAM scaling, and data-movement research intended to mature into measurable prototypes and IP.',
      phase: 'pre-work',
      phaseLabel: 'Pre-work / funding-gated flagship',
      statusState: 'director-decision',
      statusLabel: 'FUNDING GATE RECORDED',
      statusNote: 'The division is intentionally in pre-work. Its first credible milestone is a measured simulator or model against a von Neumann baseline, not a survey or product claim.',
      activationGate: 'Stable monthly revenue covers compute and time without weakening the active revenue engines.',
      operatingBoundary: 'AI Research owns research questions, validation, claims, and IP records. RickPrime does not portray research hypotheses as results.',
      sourceDocuments: [
        { label: 'AI Research operating overview', relativePath: 'AI-Research/README.md' },
        { label: 'Portfolio activation roadmap', relativePath: 'WPAI-ROADMAP.md' },
        { label: 'Empire production constitution', relativePath: 'SOULv2.0.0.md' },
      ],
    }),
    division({
      id: 'quantum',
      label: 'Quantum',
      category: 'Long-horizon research',
      directoryName: 'Quantum',
      description: 'Quantum-computation exploration intended to complement AI Research efficiency work after the earlier portfolio lanes are stable.',
      phase: 'deferred',
      phaseLabel: 'Deferred / last activation',
      statusState: 'director-decision',
      statusLabel: 'SEQUENCING GATE RECORDED',
      statusNote: 'Quantum work is deliberately last in the activation order because it has the longest route to utility and depends on stable AI Research and spare capacity.',
      activationGate: 'AI Research is running and stable, with spare capacity available for simulator work and one documented experiment.',
      operatingBoundary: 'Quantum owns experimental work and research documentation. It has no commercial or operational execution route in RickPrime.',
      sourceDocuments: [
        { label: 'Quantum operating overview', relativePath: 'Quantum/README.md' },
        { label: 'Portfolio activation roadmap', relativePath: 'WPAI-ROADMAP.md' },
      ],
    }),
    division({
      id: 'llm-lab',
      label: 'LLM Lab',
      category: 'Local AI infrastructure',
      directoryName: 'llm',
      description: 'Local-model and benchmark workspace supporting offline-first experimentation and the workstation’s Docker-hosted Ollama pathway.',
      phase: 'runtime',
      phaseLabel: 'Supporting local-AI infrastructure',
      statusState: 'verified',
      statusLabel: 'LOCAL LAB ARTIFACTS DETECTED',
      statusNote: 'RickPrime treats this as local infrastructure. Benchmark files and model folders indicate a lab workspace, not a statement of model availability or performance today.',
      activationGate: 'Available as a support capability; confirm live runtime state in Neural Nexus before relying on any model.',
      operatingBoundary: 'The LLM Lab and local runtime own benchmarks and model assets. RickPrime only queries the configured loopback Ollama endpoint.',
      sourceDocuments: [
        { label: 'LLM lab constitution', relativePath: 'llm/SOUL.md' },
        { label: 'Recorded benchmark result', relativePath: 'llm/bench-results-20260713-043704.txt' },
      ],
    }),
    division({
      id: 'workspace',
      label: 'Workspace Runtime',
      category: 'Control-plane infrastructure',
      directoryName: 'Workspace',
      description: 'Shared local runtime state for StudioOps and HellForge coordination, intentionally separated from portfolio source trees.',
      phase: 'runtime',
      phaseLabel: 'Runtime-only infrastructure',
      statusState: 'verified',
      statusLabel: 'RUNTIME BOUNDARY DETECTED',
      statusNote: 'RickPrime exposes only the bounded presence, timestamp, and file-count telemetry already used by the Operations Deck. It never reads runtime contents.',
      activationGate: 'Always local and state-driven; no launch or publication action is available from the Atlas.',
      operatingBoundary: 'StudioOps and HellForge own runtime files, approvals, and journals. RickPrime retains read-only summary access.',
      sourceDocuments: [
        { label: 'RickPrime architecture boundary', relativePath: 'Software/RickPrime/ARCHITECTURE.md' },
        { label: 'WPAI operating context', relativePath: 'WPAI-CONTEXT.md' },
      ],
    }),
    division({
      id: 'tools',
      label: 'Tools',
      category: 'Shared utilities',
      directoryName: 'Tools',
      description: 'Shared local utilities kept outside product and research ownership so operational helpers do not become an untracked side channel.',
      phase: 'support',
      phaseLabel: 'Supporting utilities',
      statusState: 'verified',
      statusLabel: 'UTILITY ROOT DETECTED',
      statusNote: 'The folder is visible to the workstation. Individual utility scope, dependencies, and release status remain owned by their local documentation.',
      activationGate: 'Available only as a support area; no generic runner is exposed by RickPrime.',
      operatingBoundary: 'Tools remain independently governed. RickPrime can open the registered root but cannot execute arbitrary utility scripts.',
      sourceDocuments: [
        { label: 'WPAI operating context', relativePath: 'WPAI-CONTEXT.md' },
        { label: 'Empire production constitution', relativePath: 'SOULv2.0.0.md' },
      ],
    }),
    division({
      id: 'archives',
      label: 'Archives',
      category: 'Historical records',
      directoryName: 'Archives',
      description: 'Historical and retained material kept outside active lanes so it remains visible without being mistaken for a live product or runtime dependency.',
      phase: 'archive',
      phaseLabel: 'Archive / non-operational',
      statusState: 'verified',
      statusLabel: 'ARCHIVE ROOT DETECTED',
      statusNote: 'Archive presence is an inventory signal only. RickPrime assigns no launch, publishing, or operational status to retained material.',
      activationGate: 'No activation gate. Restore or reuse material only through its owning project and director review.',
      operatingBoundary: 'Archives are retained records, not a default source of active requirements or executable code.',
      sourceDocuments: [
        { label: 'WPAI operating context', relativePath: 'WPAI-CONTEXT.md' },
        { label: 'Empire production constitution', relativePath: 'SOULv2.0.0.md' },
      ],
    }),
    division({
      id: 'grok-workspace',
      label: 'Grok Workspace',
      category: 'Collaboration workspace',
      directoryName: 'grok-workspace',
      description: 'A separately scoped collaboration workspace retained as a visible handoff point rather than silently folded into an active product or division.',
      phase: 'support',
      phaseLabel: 'Scoped collaboration workspace',
      statusState: 'needs-verification',
      statusLabel: 'SCOPE REQUIRES LOCAL REVIEW',
      statusNote: 'Presence is visible, but current ownership, active scope, and any runnable services must be established by the workspace’s local documentation before use.',
      activationGate: 'Use only when its local instructions and current scope are reviewed by the responsible operator.',
      operatingBoundary: 'This workspace is not automatically a company-wide execution target; RickPrime provides folder awareness only.',
      sourceDocuments: [
        { label: 'WPAI operating context', relativePath: 'WPAI-CONTEXT.md' },
        { label: 'Empire production constitution', relativePath: 'SOULv2.0.0.md' },
      ],
    }),
  ];
}

function getProjectDefinitions(wpaiRoot) {
  const softwareRoot = path.join(wpaiRoot, 'Software');
  const project = (id, label, group, directoryName, description, options = {}) => ({
    id,
    label,
    group,
    directory: path.join(softwareRoot, directoryName),
    description,
    launch: options.launch ?? null,
    parked: options.parked ?? false,
  });

  return [
    project('studioops', 'StudioOps', 'Control plane', 'StudioOps', 'Approvals, studio status, and release safeguards.'),
    project('hellforge', 'HellForge', 'Control plane', 'HellForge', 'Real PTYs, command deck, and council-bus operations.', { launch: 'hellforge' }),
    project('wpai-explorer', 'WPAI Explorer', 'Knowledge systems', 'wpai-explorer', 'The original local knowledge explorer. Its deterministic context-bundle workflow is now native in RickPrime Knowledge Forge; this folder remains the source/fallback record.'),
    project('workstation', 'Workstation', 'Knowledge systems', 'Workstation', 'The original browser workstation and creative shell.'),
    project('digichar', 'DigiChar', 'Knowledge systems', 'digichar', 'Local-first character and financial data workspace.'),
    project('py-mason', 'PyMason', 'Developer tools', 'PyMason', 'Current Python tooling project; local instructions govern edits.'),
    project('repoforge', 'RepoForge', 'Products', 'RepoForge', 'Repository-focused external product.'),
    project('mixin-field-manual', 'Mixin Field Manual', 'Products', 'MixinFieldManual', 'Mixin reference and external product.'),
    project('apode', 'APODE', 'Developer tools', 'APODE', 'Portfolio utility project.'),
    project('atoz-grabber', 'AtoZ Grabber', 'Developer tools', 'AtoZ-Grabber', 'Portfolio utility project.'),
    project('github-code-crawler', 'GitHub Code Crawler', 'Developer tools', 'GitHubCodeCrawler', 'Code exploration and crawler project.'),
    project('fuse', 'FUSE', 'Developer tools', 'FUSE', 'Portfolio utility project.'),
    project('xtechbot', 'XTechBot', 'Developer tools', 'XTechBot', 'Automation and developer utility project.'),
    project('xlang', 'XLang', 'Experiments', 'XLang', 'Language and experimentation project.'),
    project('bundle-social', 'Bundle.Social', 'Experiments', 'Bundle.Social', 'Portfolio social-product experiment.'),
    project('bitburner-scripts', 'BitBurner Scripts', 'Experiments', 'BitBurner Scripts', 'Automation and game scripting project.'),
    project('random-story-generator', 'Random Story Generator', 'Experiments', 'Random Story Generator', 'Creative-generation project.'),
    project('hidout-hunter', 'HidoutHunter', 'Experiments', 'HidoutHunter', 'Portfolio research and utility project.'),
    project('yumnom', 'YumNom', 'Parked', 'YumNom', 'Director-deferred product. RickPrime deliberately does not launch it.', { parked: true }),
  ];
}

/**
 * Research is represented as a governed registry rather than a generic runner.
 * Records can expose source availability and a human-clicked folder handoff, but
 * none may supply arbitrary commands, model pulls, web crawling, or experiment
 * execution. Janus receives the single documented read-only status probe below.
 */
function getResearchDefinitions(wpaiRoot) {
  const researchRoot = path.join(wpaiRoot, 'AI-Research');
  const research = (definition) => {
    const { directoryName, sourceDocuments, ...properties } = definition;
    return {
      ...properties,
      directory: path.join(researchRoot, directoryName),
      sourceDocuments: sourceDocuments.map(({ label, relativePath }) => source(wpaiRoot, label, relativePath)),
    };
  };
  const foundation = [
    { label: 'AI Research operating overview', relativePath: 'AI-Research/README.md' },
    { label: 'Autonomous AI architecture boundary', relativePath: 'AI-Research/AUTONOMOUS-AI-ARCHITECTURE.md' },
  ];

  return [
    research({
      id: 'asset-converter',
      label: 'AssetConverter / Omni32',
      category: 'Asset research',
      directoryName: 'AssetConverter',
      description: 'Sparse asset-conversion research and the Omni32 pipeline. Its upstream pull, commit, build, and deploy operations remain outside RickPrime.',
      phaseLabel: 'Guarded research capability',
      statusState: 'needs-verification',
      statusLabel: 'SOURCE PRESENT; EXECUTION EXCLUDED',
      statusNote: 'The repository documents a capable asset pipeline. Presence does not authorize pulls, transformations, commits, builds, or deployment from this workstation.',
      activationGate: 'Use only through the owning project after its local instructions, inputs, and human approval requirements are reviewed.',
      operatingBoundary: 'RickPrime maps the research node and its evidence only; AssetConverter owns all asset-changing behavior.',
      integrationMode: 'source-map',
      tags: ['assets', 'omni32', 'conversion', 'sparse'],
      capabilities: ['Asset-pipeline source mapping', 'Evidence availability', 'Folder handoff'],
      sourceDocuments: [
        { label: 'AssetConverter overview', relativePath: 'AI-Research/AssetConverter/README.md' },
        { label: 'AssetConverter local instructions', relativePath: 'AI-Research/AssetConverter/CLAUDE.md' },
      ],
    }),
    research({
      id: 'automation-lab',
      label: 'AutomationLab',
      category: 'Automation research',
      directoryName: 'AutomationLab',
      description: 'A registered automation research workspace whose current scope requires project-local confirmation before any operational use.',
      phaseLabel: 'Inventory / local review required',
      statusState: 'needs-verification',
      statusLabel: 'LOCAL SCOPE UNVERIFIED',
      statusNote: 'The workspace is detectable in the research root, but no runtime, capability, or external-effect claim is promoted into RickPrime.',
      activationGate: 'Read the local project authority and establish ownership before enabling any automation path.',
      operatingBoundary: 'RickPrime does not start, configure, or schedule AutomationLab processes.',
      integrationMode: 'source-map',
      tags: ['automation', 'research', 'governance'],
      capabilities: ['Registered workspace', 'Folder handoff', 'Evidence gap visibility'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'claude-playground',
      label: 'Claude Playground',
      category: 'Model experimentation',
      directoryName: 'Claude_Playground',
      description: 'A separately scoped model-experimentation workspace retained as an inventory node, not a cloud or credential integration.',
      phaseLabel: 'Inventory / local review required',
      statusState: 'needs-verification',
      statusLabel: 'NO RUNTIME BRIDGE',
      statusNote: 'RickPrime deliberately does not ingest provider credentials, remote model settings, or execution controls from this workspace.',
      activationGate: 'Local instructions and a deliberate provider/security review are required before use.',
      operatingBoundary: 'Only the owning workspace can configure external model access; RickPrime remains local-only.',
      integrationMode: 'source-map',
      tags: ['models', 'playground', 'experiments', 'credentials'],
      capabilities: ['Registered workspace', 'Folder handoff', 'Boundary visibility'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'deep-research-engine',
      label: 'Deep Research Engine',
      category: 'Research systems',
      directoryName: 'deep_research_engine',
      description: 'A research-engine workspace represented for discovery and evidence tracking, without a crawler, browser, or autonomous execution surface.',
      phaseLabel: 'Research workspace / activation gated',
      statusState: 'needs-verification',
      statusLabel: 'RUNNER NOT EXPOSED',
      statusNote: 'No live result, external source, or process status is inferred from folder presence.',
      activationGate: 'An owning-project review must define a bounded research question, data source, cost, and approval path.',
      operatingBoundary: 'RickPrime will not launch research engines or perform web collection on behalf of this node.',
      integrationMode: 'source-map',
      tags: ['research', 'synthesis', 'evidence', 'engine'],
      capabilities: ['Research mapping', 'Folder handoff', 'Evidence gap visibility'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'grok-playground',
      label: 'Grok Playground',
      category: 'Model experimentation',
      directoryName: 'Grok_Playground',
      description: 'A resource-constrained research playground with explicit claim labeling and a scientific workflow in its local documentation.',
      phaseLabel: 'Research synthesis / resource constrained',
      statusState: 'research-synthesis',
      statusLabel: 'HYPOTHESES REQUIRE MEASUREMENT',
      statusNote: 'Its local methodology informs the registry, but RickPrime does not turn research framing into a performance or deployment claim.',
      activationGate: 'Run only a funded, documented experiment under the owning workspace and hardware constraints.',
      operatingBoundary: 'Provider credentials, cloud calls, and experiment execution remain outside RickPrime.',
      integrationMode: 'source-map',
      tags: ['models', 'experiments', 'vram', 'methodology'],
      capabilities: ['Methodology source', 'Folder handoff', 'Evidence labeling'],
      sourceDocuments: [
        { label: 'Grok Playground overview', relativePath: 'AI-Research/Grok_Playground/README.md' },
        ...foundation,
      ],
    }),
    research({
      id: 'janus',
      label: 'JanusPrime',
      category: 'Research orchestration',
      directoryName: 'Janus',
      description: 'The canonical research orchestration integration joining Project-Janus, Smart Library memory, Omni32 assets, and optional REL cognition.',
      phaseLabel: 'Governed orchestration / status only',
      statusState: 'needs-verification',
      statusLabel: 'READ-ONLY STATUS AVAILABLE',
      statusNote: 'A documented status probe is available. It reports its own local dependencies but cannot create tasks, seed work, repair state, run loops, or enable research.',
      activationGate: 'The owning Janus workflow and human approval controls govern task creation, execution, spending, and research activation.',
      operatingBoundary: 'RickPrime exposes only the documented Janus status command and a folder handoff; it is not a second orchestrator or task store.',
      integrationMode: 'status-control',
      tags: ['janus', 'orchestration', 'memory', 'governance', 'status'],
      capabilities: ['Read-only status probe', 'Source provenance', 'Folder handoff'],
      sourceDocuments: [
        { label: 'Janus overview', relativePath: 'AI-Research/Janus/README.md' },
        { label: 'Janus integration instructions', relativePath: 'AI-Research/Janus/AGENTS.md' },
      ],
    }),
    research({
      id: 'operation-pinky',
      label: 'Operation Pinky and the Brain',
      category: 'Autonomy research',
      directoryName: 'Operation-Pinky and the Brain',
      description: 'A registered autonomy-research workspace with no promoted runtime or execution capability.',
      phaseLabel: 'Inventory / local review required',
      statusState: 'needs-verification',
      statusLabel: 'AUTONOMY NOT ENABLED',
      statusNote: 'RickPrime records the workspace without implying it is active, safe to run, or authorized to affect other systems.',
      activationGate: 'Its local instructions, containment, and human approval model must be reviewed before activation.',
      operatingBoundary: 'No background agent, scheduler, or automation route is exposed by RickPrime.',
      integrationMode: 'source-map',
      tags: ['autonomy', 'agents', 'research', 'containment'],
      capabilities: ['Registered workspace', 'Folder handoff', 'Boundary visibility'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'recurrsive',
      label: 'Recurrsive',
      category: 'Novel architectures',
      directoryName: 'Recurrsive',
      description: 'A recursive-computation research project with local benchmark claims that remain research evidence until independently reproduced.',
      phaseLabel: 'Research synthesis / benchmark verification',
      statusState: 'research-synthesis',
      statusLabel: 'MEASUREMENTS NEED REPRODUCTION',
      statusNote: 'Local benchmark material is available for review, not automatically adopted as a validated portfolio result.',
      activationGate: 'Reproduce the stated baseline and measurement conditions before promoting any result into a roadmap or external claim.',
      operatingBoundary: 'RickPrime neither runs benchmarks nor treats a README assertion as a verified outcome.',
      integrationMode: 'knowledge-source',
      tags: ['recursive', 'architecture', 'benchmark', 'efficiency'],
      capabilities: ['Evidence discovery', 'Knowledge Forge context', 'Folder handoff'],
      sourceDocuments: [
        { label: 'Recurrsive research overview', relativePath: 'AI-Research/Recurrsive/README.md' },
        ...foundation,
      ],
    }),
    research({
      id: 'rel-codex-variant',
      label: 'REL Codex Variant',
      category: 'Cognition research',
      directoryName: 'REL_Codex_Variant',
      description: 'An optional cognition and MCP/REST integration layer with configuration and authentication that must remain owned by its local environment.',
      phaseLabel: 'Optional integration / credentials excluded',
      statusState: 'needs-verification',
      statusLabel: 'AUTHENTICATED RUNTIME EXCLUDED',
      statusNote: 'The project can expose authenticated services, so RickPrime intentionally does not ingest endpoints, secrets, or a live client.',
      activationGate: 'Configure and authorize within the owning REL environment after a security and scope review.',
      operatingBoundary: 'No secrets, API calls, or embedded external clients enter the RickPrime bridge.',
      integrationMode: 'source-map',
      tags: ['rel', 'cognition', 'mcp', 'authentication'],
      capabilities: ['Provenance mapping', 'Folder handoff', 'Security boundary visibility'],
      sourceDocuments: [
        { label: 'REL Codex Variant overview', relativePath: 'AI-Research/REL_Codex_Variant/README.md' },
        ...foundation,
      ],
    }),
    research({
      id: 'research-crawler',
      label: 'Research Crawler',
      category: 'Research systems',
      directoryName: 'research_crawler',
      description: 'A crawler-oriented research workspace maintained as a source node without a built-in browsing, collection, or scheduling control.',
      phaseLabel: 'Inventory / execution excluded',
      statusState: 'needs-verification',
      statusLabel: 'COLLECTION NOT EXPOSED',
      statusNote: 'Folder presence does not establish permitted targets, legal scope, rate limits, or a current dataset.',
      activationGate: 'The owning project must define allowed sources, compliance, rate limits, and a human-approved run before collection.',
      operatingBoundary: 'RickPrime never initiates external crawling or turns this entry into a generic web agent.',
      integrationMode: 'source-map',
      tags: ['crawler', 'research', 'sources', 'governance'],
      capabilities: ['Registered workspace', 'Folder handoff', 'Scope visibility'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'smart-library',
      label: 'Smart Library',
      category: 'Knowledge systems',
      directoryName: 'Smart Library',
      description: 'A semantic-memory research workspace and one of the lineage sources for RickPrime Knowledge Forge context and provenance patterns.',
      phaseLabel: 'Knowledge-system source / local review',
      statusState: 'needs-verification',
      statusLabel: 'LINEAGE MAPPED; RUNTIME NOT EMBEDDED',
      statusNote: 'RickPrime adapts the bounded context-and-provenance pattern but does not import a separate memory service, hidden database, or task store.',
      activationGate: 'Any live memory backend must be configured and owned by Smart Library/Janus after local review.',
      operatingBoundary: 'Knowledge Forge uses its own fixed local registry; Smart Library remains independently operated.',
      integrationMode: 'knowledge-source',
      tags: ['knowledge', 'memory', 'semantic', 'provenance'],
      capabilities: ['Knowledge Forge lineage', 'Evidence discovery', 'Folder handoff'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'topological-hydro',
      label: 'Topological Hydro-Computational Engine',
      category: 'Novel architectures',
      directoryName: 'Topological Hydro-Computational Engine',
      description: 'A novel-computing research workspace held as an explicitly research-stage concept rather than a runtime claim.',
      phaseLabel: 'Research synthesis / funding gated',
      statusState: 'research-synthesis',
      statusLabel: 'CONCEPT REQUIRES BASELINE',
      statusNote: 'No performance or deployability claim is exposed until a controlled simulator and baseline comparison are recorded.',
      activationGate: 'Stable funding plus one documented, measured experiment against a conventional baseline.',
      operatingBoundary: 'RickPrime exposes no simulator launch or compute-allocation action for this research node.',
      integrationMode: 'knowledge-source',
      tags: ['topological', 'hydro', 'architecture', 'simulation'],
      capabilities: ['Research context', 'Evidence labeling', 'Folder handoff'],
      sourceDocuments: foundation,
    }),
    research({
      id: 'tsam',
      label: 'TSAM',
      category: 'Novel architectures',
      directoryName: 'TSAM',
      description: 'A deterministic cognitive rewrite-engine research project with a Python source environment declared in its own project metadata.',
      phaseLabel: 'Research implementation / local verification',
      statusState: 'needs-verification',
      statusLabel: 'LOCAL CONTRACT AVAILABLE',
      statusNote: 'The project metadata identifies its runtime contract, but RickPrime does not run it or infer experimental results.',
      activationGate: 'Use the owning project workflow, declared Python environment, tests, and research protocol before execution.',
      operatingBoundary: 'No Python execution path is added to RickPrime for TSAM.',
      integrationMode: 'knowledge-source',
      tags: ['tsam', 'rewrite', 'deterministic', 'cognition'],
      capabilities: ['Runtime-contract evidence', 'Knowledge Forge context', 'Folder handoff'],
      sourceDocuments: [
        { label: 'TSAM project metadata', relativePath: 'AI-Research/TSAM/pyproject.toml' },
        ...foundation,
      ],
    }),
    research({
      id: 'veriforge',
      label: 'VeriForge',
      category: 'Verification research',
      directoryName: 'VeriForge',
      description: 'An experimental Rust verification research project represented as an evidence source, not a production validation service.',
      phaseLabel: 'Experimental MVP / claim verification',
      statusState: 'research-synthesis',
      statusLabel: 'EXPERIMENTAL EVIDENCE ONLY',
      statusNote: 'Its local MVP documentation is useful context, but does not establish a production-grade verification result.',
      activationGate: 'Validate behavior, threat model, and reproducible results in the owning project before any operational adoption.',
      operatingBoundary: 'RickPrime does not invoke VeriForge or label its outcomes as portfolio-wide truth.',
      integrationMode: 'knowledge-source',
      tags: ['verification', 'rust', 'mvp', 'evidence'],
      capabilities: ['Evidence discovery', 'Knowledge Forge context', 'Folder handoff'],
      sourceDocuments: [
        { label: 'VeriForge overview', relativePath: 'AI-Research/VeriForge/README.md' },
        ...foundation,
      ],
    }),
  ];
}

function getCommandDefinitions(wpaiRoot) {
  const studioOps = path.join(wpaiRoot, 'Software', 'StudioOps');
  const softwareRoot = path.join(wpaiRoot, 'Software');
  const wpaiScript = path.join(studioOps, 'cli', 'wpai.ps1');
  const janusRoot = path.join(wpaiRoot, 'AI-Research', 'Janus');
  const janusScript = path.join(janusRoot, 'scripts', 'janus.ps1');

  return {
    'studio-status': {
      id: 'studio-status',
      label: 'Read studio status',
      description: 'Runs the existing StudioOps read-only status command.',
      executable: 'powershell.exe',
      args: ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', wpaiScript, 'status'],
      cwd: studioOps,
      timeoutMs: 45000,
    },
    'music-check': {
      id: 'music-check',
      label: 'Validate music packages',
      description: 'Runs the existing validation gate without emitting a ticket or publishing anything.',
      executable: 'powershell.exe',
      args: ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', wpaiScript, 'music', 'check'],
      cwd: studioOps,
      timeoutMs: 60000,
    },
    'software-git-pulse': {
      id: 'software-git-pulse',
      label: 'Read software git pulse',
      description: 'Checks the Software directory status without changing the worktree.',
      executable: 'git',
      args: ['status', '--short', '--branch'],
      cwd: softwareRoot,
      timeoutMs: 10000,
    },
    'janus-status': {
      id: 'janus-status',
      label: 'Read Janus status',
      description: 'Runs the documented Janus status probe without creating tasks, starting loops, or changing research state.',
      executable: 'powershell.exe',
      args: ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', janusScript, 'status'],
      cwd: janusRoot,
      timeoutMs: 45000,
    },
  };
}

module.exports = {
  getCommandDefinitions,
  getCompanyAuthoritySources,
  getDivisionDefinitions,
  getProjectDefinitions,
  getResearchDefinitions,
};
